<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { Icon } from '@iconify/vue';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';
import { storeToRefs } from 'pinia';
import { RouterLink } from 'vue-router';
import RefreshButton from '@/components/RefreshButton.vue';
import ConfirmDeleteModal from '@/components/ConfirmDeleteModal.vue';
import BatchActionBar, { type BatchAction } from '@/components/ui/tables/BatchActionBar.vue';
import { supabase } from '@/lib/supabaseClient';
import { useAuthStore } from '@/auth/stores/useAuthStore';
import { useActiveOrgStore } from '@/modules/orgs/stores/useActiveOrgStore';
import { orgService } from '@/modules/orgs/services/orgService';
import type { OrgMediaAsset } from '@/modules/orgs/types';
import { useProfileStore } from '@/modules/profiles/stores/useProfileStore';
import { ROLE_ORDER } from '@/modules/profiles/types';

const props = defineProps<{ slug?: string | string[] }>();

const normalizedSlug = computed(() => {
  if (!props.slug) return null;
  return Array.isArray(props.slug) ? props.slug[0] : props.slug;
});

const activeOrgStore = useActiveOrgStore();
const { activeOrg, activeMembership } = storeToRefs(activeOrgStore);

const authStore = useAuthStore();
const { isAdmin } = storeToRefs(authStore);

const profileStore = useProfileStore();
const { profile } = storeToRefs(profileStore);

const searchQuery = ref('');
const assets = ref<OrgMediaAsset[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);

const selectedAssetIds = ref<string[]>([]);
const disabledAssetMap = ref<Record<string, boolean>>({});
const isBatchProcessing = ref(false);

const showUploadModal = ref(false);
const uploadFiles = ref<globalThis.File[]>([]);
const uploadError = ref<string | null>(null);
const uploadProcessing = ref(false);
const HASH_CHUNK_SIZE = 8 * 1024 * 1024; // 8MB chunks keeps memory usage reasonable for huge files.
// Supabase's TUS endpoint currently requires 6MB chunks.
const TUS_CHUNK_SIZE = 6 * 1024 * 1024;

type PendingUpload = {
  /**
   * UI-only id for optimistic table rows while uploading.
   *
   * This is NOT written to Postgres. The real `media_assets.id` is a UUID generated by Postgres
   * via the column default (`gen_random_uuid()`) when we insert the row after the upload finishes.
   */
  tempId: string;
  orgId: string;
  bucket: string;
  storagePath: string;
  fileName: string;
  mimeType: string;
  fileSizeBytes: number;
  startedAt: Date;
  progress: number; // 0..1
  uploadedBytes?: number;
  uploadBps?: number;
  state: 'queued' | 'preparing' | 'uploading' | 'finalizing' | 'failed';
  errorMessage?: string;
};

const pendingUploads = ref<PendingUpload[]>([]);

const hasInFlightUploads = computed(() =>
  pendingUploads.value.some((u) => u.state !== 'failed')
);

const showDeleteModal = ref(false);
const deleteError = ref<string | null>(null);
const deleteProcessing = ref(false);

const copyStatus = ref<Record<string, 'idle' | 'copied' | 'error'>>({});
const copyResetTimers = new Map<string, number>();

const formatDate = (date?: Date | null) => {
  if (!date) return '—';
  return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(date);
};

const formatBytes = (bytes?: number | null) => {
  if (bytes == null) return '—';
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / Math.pow(1024, i);
  return `${value.toFixed(i === 0 ? 0 : 1)} ${units[i]}`;
};

const formatSpeed = (bps?: number | null) => {
  if (!bps || !Number.isFinite(bps) || bps <= 0) return '—';
  return `${formatBytes(bps)}/s`;
};

const formatDuration = (seconds?: number | null) => {
  if (seconds == null) return '—';
  if (!Number.isFinite(seconds)) return '—';
  const total = Math.max(0, Math.floor(seconds));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${String(s).padStart(2, '0')}`;
};

const canManageMedia = computed(() => {
  if (isAdmin.value) return true;
  const role = activeMembership.value?.org_role;
  if (!role) return false;
  const managerOrder = ROLE_ORDER.manager ?? Infinity;
  return (ROLE_ORDER[role] ?? Infinity) <= managerOrder;
});

const filteredAssets = computed(() => {
  const source = [...assets.value];
  if (!searchQuery.value.trim()) return source;
  const q = searchQuery.value.toLowerCase();
  return source.filter((asset) => {
    const name = asset.file_name?.toLowerCase() ?? '';
    const path = asset.storage_path?.toLowerCase() ?? '';
    const mime = asset.mime_type?.toLowerCase() ?? '';
    return name.includes(q) || path.includes(q) || mime.includes(q) || asset.id.toLowerCase().includes(q);
  });
});

const pendingAssets = computed<OrgMediaAsset[]>(() => {
  return pendingUploads.value
    .filter((upload) => !upload.errorMessage)
    .map((upload) => ({
      id: upload.tempId,
      org_id: upload.orgId,
      uploader_id: profile.value?.id ?? 'unknown',
      bucket: upload.bucket,
      storage_path: upload.storagePath,
      file_size_bytes: upload.fileSizeBytes,
      mime_type: upload.mimeType,
      duration_seconds: 0,
      checksum: '',
      source: 'upload',
      file_name: upload.fileName,
      status: upload.state === 'failed' ? 'failed' : 'uploading',
      created_at: upload.startedAt,
    }));
});

const displayAssets = computed(() => {
  // Pending uploads first, then persisted assets.
  const all = [...pendingAssets.value, ...filteredAssets.value];
  // Optional search filtering for pending uploads too.
  if (!searchQuery.value.trim()) return all;
  const q = searchQuery.value.toLowerCase();
  return all.filter((asset) => {
    const name = asset.file_name?.toLowerCase() ?? '';
    const path = asset.storage_path?.toLowerCase() ?? '';
    const mime = asset.mime_type?.toLowerCase() ?? '';
    return name.includes(q) || path.includes(q) || mime.includes(q) || asset.id.toLowerCase().includes(q);
  });
});

const pendingUploadById = computed(() => {
  const map = new Map<string, PendingUpload>();
  for (const upload of pendingUploads.value) {
    map.set(upload.tempId, upload);
  }
  return map;
});

const uploadProgressPercent = (assetId: string) => {
  const upload = pendingUploadById.value.get(assetId);
  if (!upload) return null;
  return Math.round(Math.min(1, Math.max(0, upload.progress)) * 100);
};

const pendingUploadStatusText = (assetId: string) => {
  const upload = pendingUploadById.value.get(assetId);
  if (!upload) return null;
  if (upload.state === 'queued') return 'Queued…';
  if (upload.state === 'preparing') return 'Preparing…';
  if (upload.state === 'finalizing') return 'Finalizing…';
  if (upload.state === 'failed') return 'Failed';
  return 'Uploading…';
};

const isAssetDisabled = (assetId: string) => Boolean(disabledAssetMap.value[assetId]);
const isAssetSelected = (assetId: string) => selectedAssetIds.value.includes(assetId);
const selectableAssets = computed(() => displayAssets.value.filter((asset) => !isAssetDisabled(asset.id)));
const allSelectableSelected = computed(
  () => selectableAssets.value.length > 0 && selectableAssets.value.every((asset) => isAssetSelected(asset.id))
);
const selectionCount = computed(() => selectedAssetIds.value.length);

const toggleAssetSelection = (assetId: string) => {
  if (isAssetDisabled(assetId)) return;
  if (isAssetSelected(assetId)) {
    selectedAssetIds.value = selectedAssetIds.value.filter((id) => id !== assetId);
  } else {
    selectedAssetIds.value = [...selectedAssetIds.value, assetId];
  }
};

const handleSelectAllChange = (event: globalThis.Event) => {
  const target = event.target as globalThis.HTMLInputElement | null;
  const checked = Boolean(target?.checked);
  selectedAssetIds.value = checked ? selectableAssets.value.map((asset) => asset.id) : [];
};

const clearSelection = () => {
  selectedAssetIds.value = [];
};

const loadAssets = async () => {
  if (!activeOrg.value?.id) return;
  loading.value = true;
  error.value = null;
  try {
    assets.value = await orgService.mediaAssets.listByOrganization(activeOrg.value.id);
  } catch (err) {
    assets.value = [];
    error.value = err instanceof Error ? err.message : 'Unable to load media assets right now.';
  } finally {
    loading.value = false;
  }
};

const handleRefresh = async () => {
  await loadAssets();
};

const sanitizeFileName = (name: string) => {
  const trimmed = name.trim();
  const withoutPath = trimmed.split(/[/\\]/).pop() ?? trimmed;
  return withoutPath
    .replace(/\s+/g, '-')
    .replace(/[^a-zA-Z0-9._-]/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 120);
};

const createStoragePath = (orgId: string, fileName: string) => {
  const now = new Date();
  const yyyy = String(now.getUTCFullYear());
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const safeName = sanitizeFileName(fileName);
  const uuid =
    typeof globalThis.crypto !== 'undefined' && typeof globalThis.crypto.randomUUID === 'function'
      ? globalThis.crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  // Bucket layout: matches/orgs/{orgId}/media/{yyyy}/{mm}/{uuid}_{file}
  return `orgs/${orgId}/media/${yyyy}/${mm}/${uuid}_${safeName}`;
};

const createTempUploadId = () => {
  // We generate a client-side id so the table can render a stable row (and progress bar)
  // while the storage upload is in-flight. Once the DB insert succeeds, we remove the
  // temporary row and show the persisted `media_assets` row (with DB-generated UUID).
  const uuid =
    typeof globalThis.crypto !== 'undefined' && typeof globalThis.crypto.randomUUID === 'function'
      ? globalThis.crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  return `upload-${uuid}`;
};

const resolveSupabaseStorageBaseUrl = (supabaseUrl: string) => {
  // For large uploads, Supabase recommends using the direct storage hostname:
  // `https://<project-ref>.storage.supabase.co` instead of `https://<project-ref>.supabase.co`.
  // This avoids gateway limits and improves reliability/performance.
  try {
    const url = new URL(supabaseUrl);
    const host = url.hostname;
    if (host.endsWith('.storage.supabase.co')) {
      url.pathname = '';
      url.search = '';
      url.hash = '';
      return url.toString().replace(/\/$/, '');
    }
    if (host.endsWith('.supabase.co') && !host.includes('.storage.')) {
      const projectRef = host.split('.')[0];
      url.hostname = `${projectRef}.storage.supabase.co`;
      url.pathname = '';
      url.search = '';
      url.hash = '';
      return url.toString().replace(/\/$/, '');
    }
    return supabaseUrl.replace(/\/$/, '');
  } catch {
    return supabaseUrl.replace(/\/$/, '');
  }
};

type ResumableUploadMeta = {
  orgId: string;
  bucket: string;
  fileName: string;
  fileSizeBytes: number;
  lastModified: number;
  storagePath: string;
};

const resumableUploadMetaStorageKey = (input: {
  orgId: string;
  bucket: string;
  file: globalThis.File;
}) => {
  const name = input.file.name;
  const size = input.file.size;
  const lastModified = input.file.lastModified || 0;
  return `rugbycodex:resumable-upload:${input.orgId}:${input.bucket}:${name}:${size}:${lastModified}`;
};

const readResumableUploadMeta = (key: string): ResumableUploadMeta | null => {
  if (typeof localStorage === 'undefined') return null;
  const raw = localStorage.getItem(key);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as ResumableUploadMeta;
    if (!parsed || typeof parsed.storagePath !== 'string' || parsed.storagePath.length === 0) return null;
    return parsed;
  } catch {
    return null;
  }
};

const writeResumableUploadMeta = (key: string, meta: ResumableUploadMeta) => {
  if (typeof localStorage === 'undefined') return;
  try {
    localStorage.setItem(key, JSON.stringify(meta));
  } catch {
    // ignore quota / privacy mode
  }
};

const clearResumableUploadMeta = (key: string) => {
  if (typeof localStorage === 'undefined') return;
  try {
    localStorage.removeItem(key);
  } catch {
    // ignore
  }
};

const getOrCreateResumableStoragePath = (input: {
  orgId: string;
  bucket: string;
  file: globalThis.File;
}) => {
  const key = resumableUploadMetaStorageKey(input);
  const existing = readResumableUploadMeta(key);
  if (
    existing &&
    existing.orgId === input.orgId &&
    existing.bucket === input.bucket &&
    existing.fileName === input.file.name &&
    existing.fileSizeBytes === input.file.size &&
    existing.lastModified === (input.file.lastModified || 0)
  ) {
    return { key, storagePath: existing.storagePath };
  }

  const storagePath = createStoragePath(input.orgId, input.file.name);
  writeResumableUploadMeta(key, {
    orgId: input.orgId,
    bucket: input.bucket,
    fileName: input.file.name,
    fileSizeBytes: input.file.size,
    lastModified: input.file.lastModified || 0,
    storagePath,
  });
  return { key, storagePath };
};

const uploadToSupabaseStorageWithProgress = async (input: {
  bucket: string;
  storagePath: string;
  file: globalThis.File;
  onProgress: (progress: number) => void;
  onBytesProgress?: (bytesUploaded: number, bytesTotal: number) => void;
}): Promise<void> => {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL ?? '';
  const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? '';
  if (!supabaseUrl || !supabaseAnonKey) {
    throw new Error('Supabase environment is not configured.');
  }

  const { data, error: sessionError } = await supabase.auth.getSession();
  if (sessionError) throw sessionError;
  const token = data.session?.access_token;
  if (!token) {
    throw new Error('You must be signed in to upload.');
  }

  const storageBaseUrl = resolveSupabaseStorageBaseUrl(supabaseUrl);

  // Supabase Storage TUS endpoint (resumable uploads)
  const endpoint = `${storageBaseUrl}/storage/v1/upload/resumable`;
  const fingerprint = `rugbycodex:media:${input.bucket}:${input.storagePath}`;

  await new Promise<void>((resolve, reject) => {
    const upload = new tus.Upload(input.file, {
      endpoint,
      retryDelays: [0, 3000, 5000, 10000, 20000],
      chunkSize: TUS_CHUNK_SIZE,
      uploadDataDuringCreation: true,
      removeFingerprintOnSuccess: true,
      fingerprint: () => Promise.resolve(fingerprint),
      headers: {
        authorization: `Bearer ${token}`,
        apikey: supabaseAnonKey,
        'x-upsert': 'false',
      },
      metadata: {
        bucketName: input.bucket,
        objectName: input.storagePath,
        contentType: input.file.type || 'application/octet-stream',
        cacheControl: '3600',
      },
      onError: (error) => {
        reject(error instanceof Error ? error : new Error(String(error)));
      },
      onProgress: (bytesUploaded, bytesTotal) => {
        const total = bytesTotal && bytesTotal > 0 ? bytesTotal : input.file.size;
        const progress = total > 0 ? bytesUploaded / total : 0;
        input.onProgress(Math.min(1, Math.max(0, progress)));
        input.onBytesProgress?.(bytesUploaded, total);
      },
      onSuccess: () => {
        input.onProgress(1);
        resolve();
      },
    });

    upload
      .findPreviousUploads()
      .then((previousUploads) => {
        if (previousUploads.length > 0) {
          upload.resumeFromPreviousUpload(previousUploads[0]);
        }
        upload.start();
      })
      .catch((err) => {
        reject(err instanceof Error ? err : new Error(String(err)));
      });
  });
};

const sha256Hex = async (
  file: globalThis.File,
  options: { onProgress?: (progress: number) => void } = {}
) => {
  if (file.size === 0) {
    options.onProgress?.(1);
    return bytesToHex(sha256.create().digest());
  }

  const chunkSize = HASH_CHUNK_SIZE;
  const totalBytes = file.size;
  let hashedBytes = 0;
  const hash = sha256.create();

  while (hashedBytes < totalBytes) {
    const chunk = file.slice(hashedBytes, hashedBytes + chunkSize);
    const buffer = await chunk.arrayBuffer();
    hash.update(new Uint8Array(buffer));
    hashedBytes += buffer.byteLength;
    if (options.onProgress && totalBytes > 0) {
      options.onProgress(Math.min(1, hashedBytes / totalBytes));
    }
    // Allow the UI thread to breathe for extremely large files.
    await new Promise((resolve) => setTimeout(resolve, 0));
  }

  options.onProgress?.(1);
  return bytesToHex(hash.digest());
};

const patchPendingUpload = (tempId: string, patch: Partial<PendingUpload>) => {
  pendingUploads.value = pendingUploads.value.map((upload) =>
    upload.tempId === tempId ? { ...upload, ...patch } : upload
  );
};

const uploadTelemetry = new Map<
  string,
  {
    lastAtMs: number;
    lastBytes: number;
    emaBps: number | null;
  }
>();

const updateUploadSpeed = (tempId: string, bytesUploaded: number, bytesTotal: number) => {
  const now = Date.now();
  const prev = uploadTelemetry.get(tempId);
  if (!prev) {
    uploadTelemetry.set(tempId, { lastAtMs: now, lastBytes: bytesUploaded, emaBps: null });
    patchPendingUpload(tempId, { uploadedBytes: bytesUploaded });
    return;
  }

  const dtMs = now - prev.lastAtMs;
  const deltaBytes = bytesUploaded - prev.lastBytes;
  if (dtMs <= 0 || deltaBytes < 0) {
    prev.lastAtMs = now;
    prev.lastBytes = bytesUploaded;
    patchPendingUpload(tempId, { uploadedBytes: bytesUploaded });
    return;
  }

  const instantBps = (deltaBytes / dtMs) * 1000;
  const alpha = 0.2; // EMA smoothing factor
  const emaBps = prev.emaBps == null ? instantBps : prev.emaBps * (1 - alpha) + instantBps * alpha;
  uploadTelemetry.set(tempId, { lastAtMs: now, lastBytes: bytesUploaded, emaBps });
  patchPendingUpload(tempId, { uploadedBytes: bytesUploaded, uploadBps: emaBps });

  // Keep bytesTotal referenced so TS doesn't consider it unused if used later.
  void bytesTotal;
};

const getMediaDurationSeconds = async (file: globalThis.File) => {
  const mime = file.type ?? '';
  if (!mime.startsWith('video/') && !mime.startsWith('audio/')) return 0;
  if (typeof document === 'undefined') return 0;

  const url = URL.createObjectURL(file);
  try {
    const element = document.createElement(mime.startsWith('video/') ? 'video' : 'audio');
    element.preload = 'metadata';
    element.src = url;
    const duration = await new Promise<number>((resolve) => {
      const onLoaded = () => resolve(Number.isFinite(element.duration) ? element.duration : 0);
      const onError = () => resolve(0);
      element.addEventListener('loadedmetadata', onLoaded, { once: true });
      element.addEventListener('error', onError, { once: true });
    });
    return Math.max(0, duration);
  } finally {
    URL.revokeObjectURL(url);
  }
};

const openUploadModal = () => {
  uploadFiles.value = [];
  uploadError.value = null;
  showUploadModal.value = true;
};

const closeUploadModal = () => {
  showUploadModal.value = false;
  uploadFiles.value = [];
  uploadError.value = null;
};

const MP4_MIME_TYPES = new Set(['video/mp4', 'application/mp4']);
const isMp4File = (file: globalThis.File) => {
  const nameOk = file.name.toLowerCase().endsWith('.mp4');
  if (!nameOk) return false;
  // Some browsers/OSes provide an empty type; allow it if extension is .mp4.
  if (!file.type) return true;
  return MP4_MIME_TYPES.has(file.type);
};

const handleFileChange = (event: globalThis.Event) => {
  const target = event.target as globalThis.HTMLInputElement | null;
  const files = target?.files ? Array.from(target.files) : [];
  if (files.length === 0) {
    uploadFiles.value = [];
    uploadError.value = null;
    return;
  }

  const invalid = files.filter((file) => !isMp4File(file));
  if (invalid.length > 0) {
    uploadFiles.value = [];
    uploadError.value = 'Only MP4 files are supported right now.';
    if (target) target.value = '';
    return;
  }

  uploadFiles.value = files;
  uploadError.value = null;
};

const canUpload = computed(() => uploadFiles.value.length > 0 && !uploadProcessing.value);

type UploadJob = {
  tempId: string;
  resumableKey: string;
  orgId: string;
  uploaderId: string;
  bucket: string;
  storagePath: string;
  file: globalThis.File;
  fileName: string;
  mimeType: string;
  fileSizeBytes: number;
  startedAt: Date;
};

const uploadQueue: UploadJob[] = [];
let uploadWorkerRunning = false;

const processUploadQueue = async () => {
  if (uploadWorkerRunning) return;
  uploadWorkerRunning = true;

  try {
    while (uploadQueue.length > 0) {
      const job = uploadQueue.shift();
      if (!job) break;

      // If the row was removed (e.g., page refresh), skip work.
      if (!pendingUploads.value.some((u) => u.tempId === job.tempId)) {
        uploadTelemetry.delete(job.tempId);
        continue;
      }

      patchPendingUpload(job.tempId, { state: 'preparing', progress: 0, uploadedBytes: 0, uploadBps: undefined });

      try {
        const [checksum, durationSeconds] = await Promise.all([
          sha256Hex(job.file, {
            onProgress: (progress) => {
              patchPendingUpload(job.tempId, { progress });
            },
          }),
          getMediaDurationSeconds(job.file),
        ]);

        patchPendingUpload(job.tempId, { state: 'uploading', progress: 0, uploadedBytes: 0, uploadBps: undefined });
        uploadTelemetry.delete(job.tempId);

        await uploadToSupabaseStorageWithProgress({
          bucket: job.bucket,
          storagePath: job.storagePath,
          file: job.file,
          onProgress: (progress) => {
            patchPendingUpload(job.tempId, { progress });
          },
          onBytesProgress: (bytesUploaded, bytesTotal) => {
            updateUploadSpeed(job.tempId, bytesUploaded, bytesTotal);
          },
        });

        patchPendingUpload(job.tempId, { state: 'finalizing' });
        uploadTelemetry.delete(job.tempId);

        await orgService.mediaAssets.create({
          orgId: job.orgId,
          uploaderId: job.uploaderId,
          bucket: job.bucket,
          storagePath: job.storagePath,
          fileSizeBytes: job.fileSizeBytes,
          mimeType: job.mimeType,
          durationSeconds,
          checksum,
          source: 'upload',
          fileName: job.fileName,
        });

        if (activeOrg.value?.id === job.orgId) {
          await loadAssets();
        }

        pendingUploads.value = pendingUploads.value.filter((u) => u.tempId !== job.tempId);
        clearResumableUploadMeta(job.resumableKey);
        uploadTelemetry.delete(job.tempId);
      } catch (err) {
        // Best-effort cleanup: avoid orphaned files when quota/RLS prevents inserting the DB row.
        try {
          await supabase.storage.from(job.bucket).remove([job.storagePath]);
        } catch {
          // ignore cleanup failures
        }

        patchPendingUpload(job.tempId, {
          state: 'failed',
          errorMessage: err instanceof Error ? err.message : 'Upload failed.',
        });

        uploadTelemetry.delete(job.tempId);
      }
    }
  } finally {
    uploadWorkerRunning = false;
  }
};

const handleUpload = async () => {
  if (!activeOrg.value?.id) {
    uploadError.value = 'No organization selected.';
    return;
  }
  if (!profile.value?.id) {
    uploadError.value = 'You must be signed in to upload.';
    return;
  }
  if (uploadFiles.value.length === 0) {
    uploadError.value = 'Choose a file first.';
    return;
  }

  // `uploadProcessing` is only for the modal submit UX; the queue can continue in the background.
  uploadProcessing.value = true;
  uploadError.value = null;

  const bucket = 'matches';
  const orgId = activeOrg.value.id;
  const uploaderId = profile.value.id;
  const startedAt = new Date();

  // Queue all selected files.
  const jobs: UploadJob[] = uploadFiles.value.map((file) => {
    const { key: resumableKey, storagePath } = getOrCreateResumableStoragePath({ orgId, bucket, file });
    const tempId = createTempUploadId();
    return {
      tempId,
      resumableKey,
      orgId,
      uploaderId,
      bucket,
      storagePath,
      file,
      fileName: file.name,
      mimeType: file.type || 'application/octet-stream',
      fileSizeBytes: file.size,
      startedAt,
    };
  });

  // Show queued rows immediately.
  const pendingRows: PendingUpload[] = jobs.map((job) => ({
    tempId: job.tempId,
    orgId: job.orgId,
    bucket: job.bucket,
    storagePath: job.storagePath,
    fileName: job.fileName,
    mimeType: job.mimeType,
    fileSizeBytes: job.fileSizeBytes,
    startedAt: job.startedAt,
    progress: 0,
    uploadedBytes: 0,
    state: 'queued',
  }));

  pendingUploads.value = [...pendingRows, ...pendingUploads.value];
  uploadQueue.push(...jobs);

  // Close modal immediately; uploads will process sequentially in the background.
  showUploadModal.value = false;
  uploadFiles.value = [];

  try {
    // Don't await the entire queue here; allow the user to keep using the UI and queue more.
    void processUploadQueue();
  } catch (err) {
    // Should be rare: processUploadQueue handles per-job failures.
    uploadError.value = err instanceof Error ? err.message : 'Upload failed.';
  } finally {
    uploadProcessing.value = false;
  }
};

const updateCopyStatus = (key: string, status: 'idle' | 'copied' | 'error') => {
  copyStatus.value = { ...copyStatus.value, [key]: status };
  if (typeof window === 'undefined') return;

  if (status === 'idle') {
    const timer = copyResetTimers.get(key);
    if (timer) {
      window.clearTimeout(timer);
      copyResetTimers.delete(key);
    }
    return;
  }

  const duration = status === 'copied' ? 1800 : 3000;
  const existing = copyResetTimers.get(key);
  if (existing) window.clearTimeout(existing);

  const timer = window.setTimeout(() => {
    copyResetTimers.delete(key);
    copyStatus.value = { ...copyStatus.value, [key]: 'idle' };
  }, duration);

  copyResetTimers.set(key, timer);
};

const copyToClipboard = async (key: string, text: string) => {
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
    } else if (typeof document !== 'undefined') {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    } else {
      throw new Error('Clipboard API is not available in this environment.');
    }
    updateCopyStatus(key, 'copied');
  } catch {
    updateCopyStatus(key, 'error');
  }
};

const copyLabel = (key: string) => {
  const state = copyStatus.value[key];
  if (state === 'copied') return 'Copied';
  if (state === 'error') return 'Retry copy';
  return 'Copy';
};

const openDeleteModal = () => {
  if (!selectedAssetIds.value.length) return;
  deleteError.value = null;
  showDeleteModal.value = true;
};

const closeDeleteModal = () => {
  if (deleteProcessing.value) return;
  showDeleteModal.value = false;
  deleteError.value = null;
};

const handleBatchDelete = async () => {
  openDeleteModal();
};

const confirmDelete = async () => {
  if (!selectedAssetIds.value.length) return;

  const targets = assets.value.filter((asset) => selectedAssetIds.value.includes(asset.id));
  if (!targets.length) {
    closeDeleteModal();
    return;
  }

  isBatchProcessing.value = true;
  deleteProcessing.value = true;
  deleteError.value = null;

  try {
    for (const asset of targets) {
      disabledAssetMap.value = { ...disabledAssetMap.value, [asset.id]: true };
    }

    // Delete storage first; if it fails, do not delete the DB row.
    for (const asset of targets) {
      const { error: storageError } = await supabase.storage.from(asset.bucket).remove([asset.storage_path]);
      if (storageError) {
        throw storageError;
      }
      await orgService.mediaAssets.deleteById(asset.id);
    }

    await loadAssets();
    clearSelection();
    closeDeleteModal();
  } catch (err) {
    deleteError.value = err instanceof Error ? err.message : 'Delete failed.';
  } finally {
    deleteProcessing.value = false;
    isBatchProcessing.value = false;
    disabledAssetMap.value = {};
  }
};

const batchActions = computed<BatchAction[]>(() => [
  {
    id: 'delete',
    label: 'Delete',
    icon: 'carbon:trash-can',
    variant: 'secondary',
    disabled: isBatchProcessing.value,
    onClick: handleBatchDelete,
  },
]);

watch(
  displayAssets,
  (rows) => {
    const valid = new Set(rows.filter((asset) => !isAssetDisabled(asset.id)).map((asset) => asset.id));
    selectedAssetIds.value = selectedAssetIds.value.filter((id) => valid.has(id));
  },
  { immediate: true }
);

watch(selectionCount, (count) => {
  if (count === 0 && showDeleteModal.value) {
    closeDeleteModal();
  }
});

watch(
  normalizedSlug,
  async (slug) => {
    await activeOrgStore.ensureLoaded(slug);
    await loadAssets();
  },
  { immediate: true }
);

onMounted(async () => {
  await loadAssets();
});

onBeforeUnmount(() => {
  if (typeof window === 'undefined') return;
  copyResetTimers.forEach((timer) => window.clearTimeout(timer));
  copyResetTimers.clear();
});
</script>

<template>
  <section class="container-lg space-y-6 py-5 text-white">
    <header class="space-y-1">
      <div>
        <h1 class="text-3xl font-semibold">Footage</h1>
        <p class="text-white/70">Upload and manage footage for this organization.</p>
      </div>
    </header>

    <div class="flex flex-col gap-4 rounded border border-white/10 bg-white/5 p-4">
      <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div class="relative w-full md:max-w-md">
          <Icon icon="carbon:search" class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-white/40" />
          <input
            v-model="searchQuery"
            type="search"
            placeholder="Search by filename, mime type, or path"
            class="w-full rounded border border-white/20 bg-black/40 py-3 pl-12 pr-4 text-white placeholder:text-white/40 focus:border-white focus:outline-none"
          />
        </div>
        <div class="flex flex-wrap items-center justify-end gap-2">
          <button
            type="button"
            class="flex items-center gap-2 rounded border border-white/30 px-4 py-2 text-xs font-semibold uppercase tracking-wide text-white transition hover:bg-white hover:text-black disabled:cursor-not-allowed disabled:opacity-60"
            :disabled="!canManageMedia"
            @click="openUploadModal"
          >
            <Icon icon="carbon:upload" class="h-4 w-4" />
            Upload
          </button>
          <RefreshButton size="sm" :refresh="handleRefresh" :loading="loading" title="Refresh media" />
        </div>
      </div>

      <div
        v-if="hasInFlightUploads"
        class="mt-4 rounded border border-amber-400/40 bg-amber-500/10 p-4 text-white"
      >
        <p class="font-semibold">Upload in progress</p>
        <p class="text-sm text-white/80">
          Please keep this tab open until uploads finish. Large match footage can take a while,
          and closing the tab/browser will stop the transfer.
        </p>
      </div>

      <div v-if="loading" class="rounded border border-white/15 bg-black/30 p-4 text-white/70">
        Loading media…
      </div>

      <div v-else-if="error" class="rounded border border-rose-400/40 bg-rose-500/10 p-4 text-white">
        <p class="font-semibold">{{ error }}</p>
        <p class="text-sm text-white/80">Try refreshing or check back later.</p>
      </div>

      <div v-else class="overflow-hidden rounded border border-white/10">
        <div class="overflow-x-auto">
          <table class="w-full min-w-[860px] text-left text-sm">
            <thead class="bg-white/5 text-xs uppercase tracking-wide text-white/70">
              <tr>
                <th scope="col" class="w-12 px-4 py-3">
                  <label class="flex cursor-pointer items-center gap-2">
                    <input
                      type="checkbox"
                      class="h-4 w-4 rounded border-white/40 bg-transparent text-black"
                      :checked="allSelectableSelected"
                      :disabled="selectableAssets.length === 0"
                      @change="handleSelectAllChange"
                    />
                    <span class="sr-only">Select all media</span>
                  </label>
                </th>
                <th scope="col" class="px-4 py-3">File</th>
                <th scope="col" class="px-4 py-3">Type</th>
                <th scope="col" class="px-4 py-3">Size</th>
                <th scope="col" class="px-4 py-3">Duration</th>
                <th scope="col" class="px-4 py-3">Uploaded</th>
                <th scope="col" class="px-4 py-3">Status</th>
                <th scope="col" class="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="filteredAssets.length === 0">
                <td colspan="8" class="px-4 py-6 text-center text-white/70">
                  {{ searchQuery ? 'No media matches your search.' : 'No media uploaded yet.' }}
                </td>
              </tr>

              <tr
                v-for="asset in displayAssets"
                :key="asset.id"
                :data-state="isAssetDisabled(asset.id) ? 'disabled' : isAssetSelected(asset.id) ? 'selected' : 'enabled'"
                :aria-disabled="isAssetDisabled(asset.id)"
                class="border-b border-white/10 text-white transition-colors last:border-0"
                :class="[
                  isAssetSelected(asset.id) ? 'bg-white/10' : 'hover:bg-white/5',
                  isAssetDisabled(asset.id) ? 'opacity-50' : 'cursor-pointer'
                ]"
                @click="() => toggleAssetSelection(asset.id)"
              >
                <td class="px-4 py-3">
                  <input
                    type="checkbox"
                    class="h-4 w-4 rounded border-white/40 bg-transparent"
                    :checked="isAssetSelected(asset.id)"
                    :disabled="isAssetDisabled(asset.id)"
                    @click.stop
                    @change="() => toggleAssetSelection(asset.id)"
                  />
                </td>
                <td class="px-4 py-3">
                  <p class="font-semibold">{{ asset.file_name }}</p>
                  <p class="text-xs text-white/60 font-mono">{{ asset.bucket }}/{{ asset.storage_path }}</p>
                  <div v-if="pendingUploadById.get(asset.id)" class="mt-2">
                    <div class="flex items-center justify-between text-xs text-white/60">
                      <span class="flex items-center gap-2">
                        <span
                          v-if="pendingUploadById.get(asset.id)?.state !== 'failed'"
                          class="h-3 w-3 animate-spin rounded-full border-2 border-white/30 border-t-white"
                          aria-hidden="true"
                        ></span>
                        {{ pendingUploadStatusText(asset.id) }}
                      </span>
                      <span class="whitespace-nowrap">
                        {{ uploadProgressPercent(asset.id) }}%
                        <span
                          v-if="pendingUploadById.get(asset.id)?.state === 'uploading' && pendingUploadById.get(asset.id)?.uploadBps"
                        >
                          • {{ formatSpeed(pendingUploadById.get(asset.id)?.uploadBps) }}
                        </span>
                      </span>
                    </div>
                    <div class="relative mt-1 h-1.5 w-full overflow-hidden rounded-full bg-white/10">
                      <div
                        class="h-1.5 rounded-full bg-blue-500"
                        :style="{ width: `${uploadProgressPercent(asset.id) ?? 0}%` }"
                      />
                      <div
                        v-if="pendingUploadById.get(asset.id)?.state !== 'failed'"
                        class="upload-shimmer bg-gradient-to-r from-transparent via-white/30 to-transparent"
                        aria-hidden="true"
                      ></div>
                    </div>
                  </div>
                </td>
                <td class="px-4 py-3">{{ asset.mime_type }}</td>
                <td class="px-4 py-3">{{ formatBytes(asset.file_size_bytes) }}</td>
                <td class="px-4 py-3">{{ formatDuration(asset.duration_seconds) }}</td>
                <td class="px-4 py-3">{{ formatDate(asset.created_at) }}</td>
                <td class="px-4 py-3">
                  <span
                    class="rounded-full border px-2 py-0.5 text-xs font-medium uppercase tracking-wide"
                    :class="pendingUploadById.get(asset.id)
                      ? 'border-blue-300/50 text-blue-200'
                      : asset.status === 'ready'
                        ? 'border-emerald-300/50 text-emerald-200'
                        : 'border-amber-300/50 text-amber-200'"
                  >
                    {{ pendingUploadById.get(asset.id) ? 'uploading' : asset.status }}
                  </span>
                </td>
                <td class="px-4 py-3 text-right">
                  <div class="flex items-center justify-end gap-2">
                    <RouterLink
                      v-if="normalizedSlug"
                      :to="{ name: 'V2OrgMediaAsset', params: { slug: normalizedSlug, assetId: asset.id } }"
                      class="text-xs font-semibold uppercase tracking-wide text-white/70 transition hover:text-white"
                      :aria-disabled="Boolean(pendingUploadById.get(asset.id))"
                      :tabindex="pendingUploadById.get(asset.id) ? -1 : 0"
                      @click.stop
                      @keydown.enter.stop
                      @keydown.space.stop
                    >
                      View
                    </RouterLink>
                    <span
                      v-else
                      class="text-xs font-semibold uppercase tracking-wide text-white/40"
                      aria-disabled="true"
                      title="Missing organization slug"
                    >
                      View
                    </span>
                    <button
                      type="button"
                      class="text-xs font-semibold uppercase tracking-wide text-white/70 transition hover:text-white"
                      :title="`Copy storage path ${asset.bucket}/${asset.storage_path}`"
                      @click.stop="() => copyToClipboard(asset.id, `${asset.bucket}/${asset.storage_path}`)"
                    >
                      {{ copyLabel(asset.id) }}
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <BatchActionBar
      :selected-count="selectionCount"
      :actions="batchActions"
      :cancel-disabled="isBatchProcessing"
      @cancel="clearSelection"
    />

    <teleport to="body">
      <transition name="upload-modal">
        <div
          v-if="showUploadModal"
          class="fixed inset-0 z-40 flex items-center justify-center bg-black/70 px-4"
          role="dialog"
          aria-modal="true"
          aria-label="Upload media"
          @click.self="closeUploadModal"
        >
          <div class="w-full max-w-lg overflow-hidden rounded-lg border border-white/10 bg-[#0f1016] text-white shadow-2xl">
            <header class="border-b border-white/10 px-6 py-4">
              <h2 class="text-xl font-semibold">Upload</h2>
            </header>
            <div class="space-y-4 px-6 py-5">
              <p class="text-sm text-white/70">
                Files are stored under <span class="font-mono text-white/80">matches/orgs/&lt;orgId&gt;/media/…</span>
              </p>

              <label class="block text-sm font-semibold uppercase tracking-wide text-white/60" for="org-media-file">
                File
              </label>
              <input
                id="org-media-file"
                type="file"
                multiple
                accept="video/mp4,.mp4"
                class="w-full rounded border border-white/20 bg-black/40 p-3 text-sm text-white file:mr-4 file:rounded file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-white/15"
                :disabled="uploadProcessing"
                @change="handleFileChange"
              />
              <p class="text-xs text-white/50">Supported format: MP4 only. You can select multiple files; they will upload one at a time.</p>

              <div v-if="uploadFiles.length" class="rounded border border-white/10 bg-black/30 p-3 text-sm text-white/80">
                <p class="text-white/60">Selected:</p>
                <ul class="mt-2 space-y-1">
                  <li v-for="file in uploadFiles" :key="file.name" class="flex items-center justify-between gap-3">
                    <span class="truncate">{{ file.name }}</span>
                    <span class="shrink-0 text-white/60">{{ formatBytes(file.size) }}</span>
                  </li>
                </ul>
              </div>

              <p v-if="uploadError" class="text-sm text-rose-300">{{ uploadError }}</p>
            </div>
            <div class="flex justify-end gap-3 border-t border-white/10 bg-black/40 px-6 py-4">
              <button
                type="button"
                class="rounded border border-white/30 px-5 py-2 text-sm font-semibold uppercase tracking-wide text-white transition hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-60"
                :disabled="uploadProcessing"
                @click="closeUploadModal"
              >
                Cancel
              </button>
              <button
                type="button"
                class="rounded border border-blue-500 bg-blue-600 px-5 py-2 text-sm font-semibold uppercase tracking-wide text-white transition hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-60"
                :disabled="!canUpload"
                @click="handleUpload"
              >
                <span v-if="uploadProcessing" class="flex items-center justify-center gap-2">
                  <span class="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"></span>
                  Uploading…
                </span>
                <span v-else>Upload</span>
              </button>
            </div>
          </div>
        </div>
      </transition>
    </teleport>

    <ConfirmDeleteModal
      :show="showDeleteModal"
      :item-name="selectionCount === 1 ? 'this media asset' : `${selectionCount} media assets`"
      popup-title="Delete media"
      :is-deleting="deleteProcessing"
      :error="deleteError"
      @confirm="confirmDelete"
      @cancel="closeDeleteModal"
      @close="closeDeleteModal"
    />
  </section>
</template>

<style scoped>
.upload-modal-enter-active,
.upload-modal-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}

.upload-modal-enter-from,
.upload-modal-leave-to {
  opacity: 0;
  transform: scale(0.98);
}

.upload-shimmer {
  position: absolute;
  inset: 0;
  width: 35%;
  transform: translateX(-120%);
  animation: uploadShimmer 1.1s linear infinite;
}

@keyframes uploadShimmer {
  0% {
    transform: translateX(-120%);
  }
  100% {
    transform: translateX(320%);
  }
}
</style>
